# -*- coding: utf-8 -*-
"""a108060096 week4-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xhgMeybyZNPSTNmbGUekCjgIV-8paM_6
"""

print("hello world")

"""耶！！！"""